/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.ResetTimerStatement;

import su.nsk.iae.post.vcgenerator.*;
import java.util.List;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reset Timer Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ResetTimerStatementImpl extends StatementImpl implements ResetTimerStatement
{
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResetTimerStatementImpl()
	{
		super();
	}

	@Override
	public List<Path> applyTo(List<Path> paths, VCGeneratorState globVars) {
		for (Path path: paths)
			  path.resetTimer(this, globVars);
		return paths;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return PoSTPackage.Literals.RESET_TIMER_STATEMENT;
	}

} //ResetTimerStatementImpl
