/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST.impl;

import java.util.List;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.StartProcessStatement;
import su.nsk.iae.post.vcgenerator.Path;
import su.nsk.iae.post.vcgenerator.VCGeneratorState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Start Process Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StartProcessStatementImpl extends ProcessStatementsImpl implements StartProcessStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StartProcessStatementImpl()
  {
    super();
  }
  
	@Override
	public List<Path> applyTo(List<Path> paths, VCGeneratorState globVars) {
		for (Path path: paths)
			  path.startProcess(this, null);
		return paths;
	}

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.START_PROCESS_STATEMENT;
  }

} //StartProcessStatementImpl
