/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST.impl;

import java.util.List;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.SubprogramControlStatement;
import su.nsk.iae.post.vcgenerator.Path;
import su.nsk.iae.post.vcgenerator.VCGeneratorState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subprogram Control Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SubprogramControlStatementImpl extends StatementImpl implements SubprogramControlStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubprogramControlStatementImpl()
  {
    super();
  }
  
  @Override
  public List<Path> applyTo(List<Path> paths, VCGeneratorState globVars) {
	  for (Path path: paths)
		  path.doReturn();
	  return paths;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.SUBPROGRAM_CONTROL_STATEMENT;
  }

} //SubprogramControlStatementImpl
