/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.SymbolicVariable;
import su.nsk.iae.post.vcgenerator.ComplexTerm;
import su.nsk.iae.post.vcgenerator.DataType;
import su.nsk.iae.post.vcgenerator.FunctionSymbol;
import su.nsk.iae.post.vcgenerator.Term;
import su.nsk.iae.post.vcgenerator.VCGeneratorState;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Symbolic Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SymbolicVariableImpl extends VariableImpl implements SymbolicVariable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SymbolicVariableImpl()
  {
    super();
  }
  
  @Override
  public Term generateVariable(Term currentState, VCGeneratorState globVars) {
		String varType = globVars.getVarType(name);
		su.nsk.iae.post.vcgenerator.Constant varNameCode = globVars.getVariable(name);
		if ("BOOL".equals(varType))
			return new ComplexTerm(DataType.BOOL, FunctionSymbol.getVarBool, currentState, varNameCode);
		else if (isIntegerTypeName(varType))
			return new ComplexTerm(DataType.INT, FunctionSymbol.getVarInt, currentState, varNameCode);
		else if (isRealTypeName(varType))
			return new ComplexTerm(DataType.REAL, FunctionSymbol.getvarReal, currentState, varNameCode);
		else // TIME 
			return new ComplexTerm(DataType.INT, FunctionSymbol.getVarInt, currentState, varNameCode);
	}
  
  public static boolean isIntegerTypeName(String typeName) {
		return "SINT".equals(typeName) 
				|| "INT".equals(typeName) 
				|| "DINT".equals(typeName) 
				|| "LINT".equals(typeName)
				|| "USINT".equals(typeName)
				|| "UINT".equals(typeName)
				|| "UDINT".equals(typeName)
				|| "ULINT".equals(typeName);
	}
	
	public static boolean isRealTypeName(String typeName) {
		return "REAL".equals(typeName) || "LREAL".equals(typeName);

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.SYMBOLIC_VARIABLE;
  }

} //SymbolicVariableImpl
