/*
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPoSTScopeProvider extends DelegatingScopeProvider {
}
