package su.nsk.iae.post.generator;

import com.google.inject.Injector;
import com.google.inject.Provider;
import java.util.ArrayList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import su.nsk.iae.post.PoSTStandaloneSetup;
import su.nsk.iae.post.poST.Model;
import su.nsk.iae.post.vcgenerator.ComplexTerm;
import su.nsk.iae.post.vcgenerator.Constant;
import su.nsk.iae.post.vcgenerator.FunctionSymbol;
import su.nsk.iae.post.vcgenerator.Term;
import su.nsk.iae.post.vcgenerator.TermFactory;
import su.nsk.iae.post.vcgenerator.Variable;

@RunWith(XtextRunner.class)
@SuppressWarnings("all")
public class PoSTGeneratorTest {
  private Injector injector = new PoSTStandaloneSetup().createInjectorAndDoEMFRegistration();

  ParseHelper<Model> parser = ((ParseHelper) ((Provider) this.injector.<ParseHelper>getProvider(ParseHelper.class)).get());

  private PoSTGenerator generator = new PoSTGenerator();

  @Test
  public void testGenerateVariableCode() {
    final Constant varCode = new Constant("a", Integer.valueOf(2));
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("abbreviation a :: variable where \"a \\<equiv> (Suc (Suc 0))\"");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateVariableCode(varCode);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateProcessCode() {
    final Constant varCode = new Constant("p", Integer.valueOf(2));
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("abbreviation p :: process where \"p \\<equiv> 2\"");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateProcessCode(varCode);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateProcessStateCode() {
    final Constant varCode = new Constant("s", Integer.valueOf(2));
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("abbreviation s :: pstate where \"s \\<equiv> 2\"");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateProcessStateCode(varCode);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateConstant() {
    final Constant constant = new Constant("a", Integer.valueOf(2));
    final String type = "SINT";
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("abbreviation a :: int where \"a \\<equiv> 2\"");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateConstant(type, constant);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateStateDataTypeBoolEnvVar() {
    final ArrayList<String> envVarTypes = CollectionLiterals.<String>newArrayList("BOOL");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("datatype state =");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("emptyState |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("toEnv state |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarBool state variable bool |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarInt state variable int |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarReal state variable real |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayBool state variable int bool |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayInt state variable int int |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayReal state variable int real |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarAny state bool |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setPstate state process pstate |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("reset state process");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateStateDataType(envVarTypes);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateStateDataTypeIntEnvVar() {
    final ArrayList<String> envVarTypes = CollectionLiterals.<String>newArrayList("INT");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("datatype state =");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("emptyState |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("toEnv state |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarBool state variable bool |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarInt state variable int |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarReal state variable real |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayBool state variable int bool |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayInt state variable int int |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarArrayReal state variable int real |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setVarAny state int |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("setPstate state process pstate |");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("reset state process");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateStateDataType(envVarTypes);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateVC() {
    final FunctionSymbol inv = new FunctionSymbol("inv", true);
    final Variable s0 = new Variable("s0");
    ComplexTerm _complexTerm = new ComplexTerm(inv, s0);
    Term _env = TermFactory.toEnv(s0);
    ComplexTerm _complexTerm_1 = new ComplexTerm(inv, _env);
    final Term vc = TermFactory.impl(_complexTerm, _complexTerm_1);
    final int num = 1;
    final ArrayList<FunctionSymbol> functionParams = CollectionLiterals.<FunctionSymbol>newArrayList(inv);
    final ArrayList<Variable> variableParams = CollectionLiterals.<Variable>newArrayList(s0);
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("definition VC1 where");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"VC1 inv s0 \\<equiv>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("(");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("(inv");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("s0");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(")");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("-->");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("(inv");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("(toEnv");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("s0");
    _builder.newLine();
    _builder.append("      ");
    _builder.append(")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(")");
    _builder.newLine();
    _builder.append("  ");
    _builder.append(")");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"");
    _builder.newLine();
    final String expected = _builder.toString();
    final String result = this.generator.generateVC(vc, num, functionParams, variableParams);
    Assert.assertEquals(expected, result);
  }

  @Test
  public void testGenerateTheoryConstantsInTimeout() {
    try {
      final String theoryName = "TestTheory";
      Constant _constant = new Constant("a", Integer.valueOf(1));
      final ArrayList<Constant> envVars = CollectionLiterals.<Constant>newArrayList(_constant);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("PROGRAM Program");
      _builder.newLine();
      _builder.append("VAR_INPUT");
      _builder.newLine();
      _builder.append("a: BOOL;");
      _builder.newLine();
      _builder.append("END_VAR");
      _builder.newLine();
      _builder.append("VAR_OUTPUT");
      _builder.newLine();
      _builder.append("b: BOOL;");
      _builder.newLine();
      _builder.append("END_VAR");
      _builder.newLine();
      _builder.append("VAR CONSTANT");
      _builder.newLine();
      _builder.append("t: TIME := T#1s;");
      _builder.newLine();
      _builder.append("END_VAR");
      _builder.newLine();
      _builder.append("PROCESS process1");
      _builder.newLine();
      _builder.append("STATE state1");
      _builder.newLine();
      _builder.append("TIMEOUT t THEN");
      _builder.newLine();
      _builder.append("END_TIMEOUT");
      _builder.newLine();
      _builder.append("END_STATE");
      _builder.newLine();
      _builder.append("END_PROCESS");
      _builder.newLine();
      _builder.append("END_PROGRAM");
      _builder.newLine();
      _builder.append("CONFIGURATION Conf");
      _builder.newLine();
      _builder.append("RESOURCE Res1 ON TestCPU");
      _builder.newLine();
      _builder.append("TASK T1 (INTERVAL := T#100ms, PRIORITY := 1);");
      _builder.newLine();
      _builder.append("PROGRAM program1 WITH T1: Program;");
      _builder.newLine();
      _builder.append("END_RESOURCE");
      _builder.newLine();
      _builder.append("END_CONFIGURATION");
      _builder.newLine();
      final String programText = _builder.toString();
      final Model model = this.parser.parse(programText);
      this.generator.setModel(model);
      this.generator.setTheoryName(theoryName);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("theory ");
      _builder_1.append(theoryName);
      _builder_1.append(" imports Complex_Main");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("begin");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("type_synonym variable = nat");
      _builder_1.newLine();
      _builder_1.append("type_synonym process = nat");
      _builder_1.newLine();
      _builder_1.append("type_synonym pstate = nat");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation a :: variable where \"a \\<equiv> (Suc 0)\"");
      _builder_1.newLine();
      _builder_1.append("abbreviation b :: variable where \"b \\<equiv> (Suc (Suc 0))\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation process1 :: process where \"process1 \\<equiv> 1\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation STOP:: pstate where \"STOP \\<equiv> 0\"");
      _builder_1.newLine();
      _builder_1.append("abbreviation ERROR:: pstate where \"ERROR \\<equiv> 1\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation process1\'state1 :: pstate where \"process1\'state1 \\<equiv> 2\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation t :: int where \"t \\<equiv> 1000\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("abbreviation t\'TIMEOUT :: int where \"t\'TIMEOUT \\<equiv> 10\"");
      _builder_1.newLine();
      _builder_1.newLine();
      String _generateStateDataType = this.generator.generateStateDataType(CollectionLiterals.<String>newArrayList("BOOL"));
      _builder_1.append(_generateStateDataType);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarBoolFunction = this.generator.generateGetVarBoolFunction(envVars, envVars);
      _builder_1.append(_generateGetVarBoolFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarIntFunction = this.generator.generateGetVarIntFunction(envVars, CollectionLiterals.<Constant>newArrayList());
      _builder_1.append(_generateGetVarIntFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarRealFunction = this.generator.generateGetVarRealFunction(envVars, CollectionLiterals.<Constant>newArrayList());
      _builder_1.append(_generateGetVarRealFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarArrayBoolFunction = this.generator.generateGetVarArrayBoolFunction(envVars);
      _builder_1.append(_generateGetVarArrayBoolFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarArrayIntFunction = this.generator.generateGetVarArrayIntFunction(envVars);
      _builder_1.append(_generateGetVarArrayIntFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetVarArrayRealFunction = this.generator.generateGetVarArrayRealFunction(envVars);
      _builder_1.append(_generateGetVarArrayRealFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateGetPstateFunction = this.generator.generateGetPstateFunction(envVars);
      _builder_1.append(_generateGetPstateFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateSubstateFunction = this.generator.generateSubstateFunction(envVars);
      _builder_1.append(_generateSubstateFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateToEnvNumFunction = this.generator.generateToEnvNumFunction(envVars);
      _builder_1.append(_generateToEnvNumFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateToEnvPFunction = this.generator.generateToEnvPFunction();
      _builder_1.append(_generateToEnvPFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateLtimeFunction = this.generator.generateLtimeFunction(envVars);
      _builder_1.append(_generateLtimeFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generatePredEnvFunction = this.generator.generatePredEnvFunction(envVars);
      _builder_1.append(_generatePredEnvFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      String _generateShiftFunction = this.generator.generateShiftFunction();
      _builder_1.append(_generateShiftFunction);
      _builder_1.newLineIfNotEmpty();
      _builder_1.newLine();
      _builder_1.append("(*Verification conditions*)");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("definition VC1 where");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"VC1 inv\' s0\' \\<equiv>");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("=");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(toEnv");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(setPstate");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("emptyState");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1\'state1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("-->");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("definition VC2 where");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"VC2 inv\' env\' s0\' a\'value \\<equiv>");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(env\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(getPstate");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("=");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1\'state1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("t\'TIMEOUT");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("<=");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(ltime");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("-->");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(toEnv");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("definition VC3 where");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"VC3 inv\' env\' s0\' a\'value \\<equiv>");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(env\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(getPstate");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("=");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1\'state1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(\\<not>");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("t\'TIMEOUT");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("<=");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(ltime");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("              ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("-->");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(toEnv");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("definition VC4 where");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"VC4 inv\' env\' s0\' a\'value \\<equiv>");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(env\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(getPstate");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("=");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("STOP");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("-->");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(toEnv");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("definition VC5 where");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"VC5 inv\' env\' s0\' a\'value \\<equiv>");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(env\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("\\<and>");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(getPstate");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("            ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("process1");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("=");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("ERROR");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("-->");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("(inv\'");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append("(toEnv");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append("(setVarAny");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("s0\'");
      _builder_1.newLine();
      _builder_1.append("          ");
      _builder_1.append("a\'value");
      _builder_1.newLine();
      _builder_1.append("        ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("      ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append(")");
      _builder_1.newLine();
      _builder_1.append("  ");
      _builder_1.append("\"");
      _builder_1.newLine();
      _builder_1.append("end");
      _builder_1.newLine();
      final String expected = _builder_1.toString();
      final String result = this.generator.generateTheory();
      Assert.assertEquals(expected, result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
