/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

import su.nsk.iae.post.vcgenerator.*;
import java.util.List;
import java.util.ArrayList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
	List<Path> applyTo(List<Path> paths, VCGeneratorState globVars);
} // Statement
