/**
 * generated by Xtext 2.28.0
 */
package su.nsk.iae.post.poST;

import su.nsk.iae.post.vcgenerator.*;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbolic Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getSymbolicVariable()
 * @model
 * @generated
 */
public interface SymbolicVariable extends Variable
{
	Term generateVariable(Term currentState, VCGeneratorState globVars);
} // SymbolicVariable
